[package]
name = "device-register"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device-register-impl = { path = "./device-register-impl", version = "0.1.0" }

modular-bitfield = "0.11.2"
